### ISSUE TITLE
Add support for supertypes, subtypes and types

### ISSUE THREAD

**Issue by SilvioPilato** [MagicTheGathering/mtg-sdk-javascript#18]
Hello everyone!

Since tomorrow morning I tried to implement the types.all() function, as I need for a personal project. 
I worked on it today and I ended creating this functionality for types, subtypes and supertypes as I thought the code footprint would be minimal (as I think it actually is).

It's ok for you if I go for a pull request, or maybe it could be better better if I write some addictional tests before?
FYI here is the repository: https://github.com/SilvioPilato/mtg-sdk-javascript/tree/feature/unqueryable

Thank you!

**Comment by raineorshine** [comment]
Looks great! Went through the changes in your commit and would love a PR.
