### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by sunsheeppoplar** [MagicTheGathering/mtg-sdk-javascript#2]
Hey, I'm a junior developer looking to contribute to this project. I'm wondering where I should start looking as far as maybe checking out the other SDKs (I'm familiar with Ruby, too) in seeing what needs to be done on the JS side. Thanks!

**Comment by raineorshine** [comment]
Hi Abner! Thanks for wanting to contribute!

Currently the only function exposed in the javascript api is `card()`. An obvious endpoint to add would be `set()` to [find a set by code](https://github.com/MagicTheGathering/mtg-sdk-ruby#find-a-set-by-code). The same could be done for the `types`, `subtypes`, and `supertypes` apis. A good starting point would be to add unit tests for the missing features, then building them in TDD style.

Let me know if you have any questions along the way, I'm happy to support you!

**Comment by sunsheeppoplar** [comment]
Hey Raine. Thanks for answering back so quickly. I'm looking through the test suite now. To be honest, I haven't done a whole lot of TDD before but am familiar with some aspects of it and have done some basic stuff with RSpec. Anything you think would be helpful to read for Chai in particular before jumping in?

**Comment by raineorshine** [comment]
It really depends on your understanding of unit testing. If the overall
concept is fuzzy, I would suggest finding some general intro tutorials on
unit testing. If you mostly just need to understand the syntax of chai,
read up on the documentation. Look through the tests of this project again
and notice how they call library functions and compare the results with
hardcoded values to prove that they do what they intend.

mocha is the test runner (what runs the tests, parsing "describe" and "it"
blocks to generate coherent output) and chai is the assertion library
(giving you the functions to assert that values are equal, unequal, have a
given property, have a given type, etc).

You are welcome to ask me questions for anything that is confusing to you!

**Comment by thebergamo** [comment]
Hi! This project is awesome!

Can you add a roadmap and the apis must be added?

I want to contribute to this project too :D

**Comment by raineorshine** [comment]
@thebergamo Thanks for your interest in contributing! I created a [CONTRIBUTING.md](https://github.com/MagicTheGathering/mtg-sdk-javascript/blob/master/CONTRIBUTING.md) with a roadmap. Let me know if you have any questions or if there is any part of the process I can make clearer.

Note: I think [querybuilder.js](https://github.com/MagicTheGathering/mtg-sdk-javascript/blob/master/src/querybuilder.js) is set up in a way that it would work for both the `card` and `set` APIs. If that's the case, adding support for `set` may only be a matter of adding `set: qb('set')` to [index.js](https://github.com/MagicTheGathering/mtg-sdk-javascript/blob/master/src/index.js). Creating unit tests and making this change could be an easy way to get started!

**Comment by adback03** [comment]
Closing this because @raineorshine's latest comment seems to cover everything. The addition of the [CONTRIBUTING.md](https://github.com/MagicTheGathering/mtg-sdk-javascript/blob/master/CONTRIBUTING.md) should also help answer any future questions about contributing.
